baseURL = 'https://jimholcomb.com'
languageCode = 'en-us'
title = 'Jim Holcomb Home'
theme = "ananke"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    name = "Search"
    url = "https://search.jimholcomb.com"
    weight = 4

