baseURL = 'https://jimholcomb.com'
languageCode = 'en-us'
#title = 'Jim Holcomb Home'
theme = "ananke"
#theme = "paper"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30
  [[menu.main]]
    name = "Search"
    url = "https://search.jimholcomb.com"
    weight = 40

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Old Dog. New Tricks"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
recent_posts_number = 3